### ISSUE TITLE
acrescentar a Mirella Moro como keynote da conferência

### ISSUE THREAD

**Issue by juliomfreitas** [pythonsudeste/pythonsudeste2016-site#30]
em sua pagina do DCC tem fotografia e uma boa biografia

**Comment by igr-santos** [comment]
@juliomfreitas a foto lá está pequena, seria interessante pedir a ela uma foto para ficar melhor no encaixe do site, e já aproveita e pede uma descrição

**Comment by cassiobotaro** [comment]
@igr-santos @juliomfreitas  Acho que podemos considerar esta issue concluida?
